# Generated by Django 2.2.6 on 2019-10-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoestore', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a test description'),
            preserve_default=False,
        ),
    ]
