# Generated by Django 2.2.6 on 2019-10-31 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoestore', '0009_auto_20191031_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('goods', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['category']},
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('CL', 'Casuals'), ('BT', 'Boots'), ('OF', 'Official'), ('CS', 'Closed shoes'), ('OS', 'Open shoes'), ('SW', 'Sport wear'), ('OW', 'Out wear')], max_length=2),
        ),
    ]
