# Generated by Django 2.2.6 on 2019-11-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoestore', '0010_auto_20191031_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('S', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=1),
        ),
    ]
